-- 코드를 입력하세요
SELECT B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * A.SALES) AS TOTAL_SALES
FROM BOOK_SALES A
INNER JOIN BOOK B on A.BOOK_ID = B.BOOK_ID
INNER JOIN AUTHOR C on B.AUTHOR_ID = C.AUTHOR_ID
WHERE DATE_FORMAT(A.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC